version: '3.8'
# Based on post:
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/

services:
  web:
    build: ./python/walterone
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./python/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
