# Generated by Django 4.0.4 on 2022-08-23 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('damage', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
                ('neighbors', models.ManyToManyField(blank=True, to='api.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ia')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life', models.IntegerField(default=50)),
                ('alive', models.BooleanField(default=True)),
                ('ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ia')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('where_am_i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='ias',
            field=models.ManyToManyField(through='api.MatchIA', to='api.ia'),
        ),
        migrations.AddField(
            model_name='match',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map'),
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ia')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield', models.IntegerField(default=4)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.TimeField(auto_now=True)),
                ('match_ia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defend', to='api.matchia')),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('damage', models.IntegerField(default=10)),
                ('attack_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_from', to='api.ia')),
                ('attack_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_to', to='api.ia')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='matchia',
            constraint=models.UniqueConstraint(fields=('ia', 'match'), name='match_ia'),
        ),
    ]
