# Generated by Django 4.0.4 on 2022-08-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attack',
            name='attack_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_from', to='api.ia'),
        ),
        migrations.AlterField(
            model_name='attack',
            name='attack_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attack_to', to='api.ia'),
        ),
    ]
