# Generated by Django 4.0.4 on 2022-08-19 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defend',
            name='match_ia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defend', to='api.matchia'),
        ),
    ]
