# Generated by Django 4.0.4 on 2022-06-01 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.map')),
            ],
        ),
    ]
