# Generated by Django 4.0.4 on 2022-09-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchia',
            name='life',
            field=models.IntegerField(default=200),
        ),
    ]
