# Generated by Django 4.0.4 on 2022-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_defend_match_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchia',
            name='alive',
            field=models.BooleanField(default=True),
        ),
    ]
