# Generated by Django 4.0.4 on 2022-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='neighbors',
            field=models.ManyToManyField(to='api.zone'),
        ),
    ]
