# Generated by Django 4.0.4 on 2022-10-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_matchia_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
