# Generated by Django 4.0.4 on 2022-08-16 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attack_attack_from_alter_attack_attack_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='ia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ia'),
        ),
    ]
