# Generated by Django 4.0.4 on 2022-10-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_zone_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchia',
            name='lucky_unlucky',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='lucky_unlucky',
            field=models.BooleanField(default=False),
        ),
    ]
