# Generated by Django 4.0.4 on 2022-08-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_move_ia'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='matchia',
            constraint=models.UniqueConstraint(fields=('ia', 'match'), name='match_ia'),
        ),
    ]
