# Generated by Django 4.0.4 on 2022-10-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_matchia_lucky_unlucky_zone_lucky_unlucky'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchia',
            name='go_ryu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zone',
            name='go_ryu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='zone',
            name='karin_gift',
            field=models.BooleanField(default=False),
        ),
    ]
