# Generated by Django 4.0.4 on 2022-06-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ia')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='ias',
            field=models.ManyToManyField(through='api.MatchIA', to='api.ia'),
        ),
        migrations.AddField(
            model_name='matchia',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match'),
        ),
    ]
