# Generated by Django 4.0.4 on 2022-08-16 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_matchia_match_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='defend',
            name='ia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ia'),
        ),
        migrations.AddConstraint(
            model_name='defend',
            constraint=models.UniqueConstraint(fields=('ia', 'match'), name='match_ia_defend'),
        ),
    ]
