# Generated by Django 4.0.4 on 2022-10-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_matchia_go_ryu_zone_go_ryu_zone_karin_gift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='damage',
            field=models.IntegerField(default=12),
        ),
    ]
