# Generated by Django 4.0.4 on 2022-08-18 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_defend_ia_defend_match_ia_defend'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='ia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ia'),
        ),
    ]
