# Generated by Django 4.0.4 on 2022-06-01 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_matchia_match_ias_matchia_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('match_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matchia')),
                ('to_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('match_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matchia')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Defend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('shield', models.IntegerField(default=4)),
                ('active', models.BooleanField(default=False)),
                ('match_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matchia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.TimeField(auto_now_add=True)),
                ('damage', models.IntegerField(default=10)),
                ('attack_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ia')),
                ('match_ia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.matchia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
