# Generated by Django 4.0.4 on 2022-08-19 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_find_ia'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchia',
            name='where_am_i',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.zone'),
        ),
        migrations.AddField(
            model_name='move',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
