# Generated by Django 4.0.4 on 2023-10-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_match_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ia',
            name='role',
            field=models.CharField(choices=[('BergenToy', 'BergenToy'), ('Player', 'Player')], default='Player', max_length=32),
        ),
    ]
