# Generated by Django 4.0.4 on 2023-10-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ia_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_from', models.CharField(default='', max_length=20)),
                ('attack_to', models.CharField(default='', max_length=20)),
                ('compute_damage', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
