# Generated by Django 4.0.4 on 2022-07-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_matchia_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='neighbors',
            field=models.ManyToManyField(blank=True, to='api.zone'),
        ),
    ]
