# Generated by Django 4.0.4 on 2023-10-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_finaldamage'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldamage',
            name='attack_from_role',
            field=models.CharField(default='BergenToy', max_length=20),
        ),
        migrations.AddField(
            model_name='finaldamage',
            name='attack_to_role',
            field=models.CharField(default='BergenToy', max_length=20),
        ),
        migrations.AddField(
            model_name='finaldamage',
            name='match_id',
            field=models.IntegerField(default=2),
        ),
    ]
